name: Daily Commit, PR, and Issue

on:
  schedule:
    - cron: '0 0 * * *'  # once daily at 00:00 UTC
  workflow_dispatch:

jobs:
  auto-commit-pr-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make a change to daily.txt
        run: |
          echo "Daily ping: $(date -u)" >> daily.txt

      - name: Commit changes on new branch (force push safe)
        id: commit_changes
        run: |
          BRANCH="daily-update-$(date +%Y-%m-%d)"
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B "$BRANCH"
          git add daily.txt
          git commit -m "🤖 Daily update on $(date -u)" || echo "Nothing to commit"
          git push origin "$BRANCH" --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue (via API)
        id: create_issue
        run: |
          ISSUE_NUMBER=$(gh api repos/marco13-moo/cron-actions/issues \
            -f title="Daily Issue $(date +%Y-%m-%d)" \
            -f body="Automatically created daily issue" \
            --jq '.number')
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request linked to issue (via API)
        id: create_pr
        run: |
          PR_NUMBER=$(gh api repos/marco13-moo/cron-actions/pulls \
            -f title="Daily PR $(date +%Y-%m-%d)" \
            -f body="Daily automated PR\n\nCloses #${{ steps.create_issue.outputs.issue_number }}" \
            -f head="${{ steps.commit_changes.outputs.branch_name }}" \
            -f base="main" \
            --jq '.number')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge pull request instantly
        run: |
          gh api repos/marco13-moo/cron-actions/pulls/${{ steps.create_pr.outputs.pr_number }}/merge \
            -f merge_method=merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete branch after merge
        run: |
          gh api \
            -X DELETE \
            "repos/marco13-moo/cron-actions/git/refs/heads/${{ steps.commit_changes.outputs.branch_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
